@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}

# CREATE USER
POST http://{{host}}/user
content-type: application/json

{
  "email": "test@mail.com",
  "password": "Welcome1982+"
}

###

# LOGIN
# @name login
POST http://{{host}}/auth/login?refresh=true
content-type: application/json

{
  "email": "test@mail.com",
  "password": "Welcome1982+"
}

@access_token = {{login.response.body.accessToken}}

###

# Refresh Token
# @name refresh
POST http://{{host}}/auth/token
content-type: application/json

{
  "email": "test@mail.com"
}

###

# LIST USERS
# @name users
GET http://{{host}}/user

@user_id = {{users.response.body.users[0].id}}

###

# GET USER BY ID
GET http://{{host}}/user/{{user_id}}

###

# DELETE USER BY ID
DELETE http://{{host}}/user/{{user_id}}
