@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

GET http://{{host}}/user

###

GET http://{{host}}/user/1

###

POST http://{{host}}/user
content-type: application/json

{
  "email": "test@mail.com",
  "password": "Welcome1982_",
  "role": "user"
}

###

DELETE http://{{host}}/user/1

###

POST http://{{host}}/auth/login
content-type: application/json

{
  "email": "test@mail.com",
  "password": "Welcome1982_"
}
